#define _GNU_SOURCE

#include <sys/mman.h>
#include <sys/random.h>
#include <unistd.h>
#include <stdio.h>
#include <stdlib.h>
#include <stdint.h>
#include <stdbool.h>
#include <stddef.h>
#include <time.h>
#include "secure_utils.h"
#include "utils.h"

static size_t _generate_random_number(size_t upper_bound) {
    unsigned int raw_bytes;

    ssize_t result = getrandom(&raw_bytes, sizeof(raw_bytes), 0); 

    if (result < 0) {
        return -1;
    }

    unsigned int final_number = raw_bytes % (upper_bound + 1);

    return final_number;
}

bool add_size_t_safely(size_t num1, size_t num2, size_t* result) {
    *result = num1 + num2;

    if (*result < num1) 
        return false; 

    return true;
}

/*
    create_guarded_region returns a memory region surrounded by guard pages.

    Layout:

        | leading guard page |
        | randomized padding |
        | user allocation    |
        | remaining padding  |
        | trailing guard page|

    mmap_base: The base of the multi-page allocation. This points
               to the start of a guard page.

    usable_ptr: A pointer to the start of the usable region. 

    offset: If requested, a randomly generated byte offset is added to 
            usable_ptr. Otherwise, offset is zero.
    
    total_size: This is the total size of the entire allocation including guard pages.

    The pointer returned to the user is usable_ptr + offset.
*/
struct guarded_region create_guarded_region(size_t length, bool add_offset) {
    long page_size = sysconf(_SC_PAGESIZE);

    // Round payload up to nearest page boundary
    size_t rounded_payload_size = round_to_nearest_page(length);

    size_t offset = 0;
    if (add_offset) {
        offset = _generate_random_number(rounded_payload_size);

        size_t alignment = _Alignof(max_align_t);
        size_t sum = 0;
        if (!add_size_t_safely(offset, alignment - 1, &sum))   
            _exit(127);

        offset = (sum) & ~(alignment - 1);
    }

    size_t new_payload_size = 0;
    if (!add_size_t_safely(rounded_payload_size, offset, &new_payload_size))
        _exit(127); 

    rounded_payload_size = round_to_nearest_page(new_payload_size);
    
    // The total region is the requested length + 2 guard pages
    size_t total_size = 0; 
    if (!add_size_t_safely(rounded_payload_size, 2 * page_size, &total_size)) 
        _exit(127);

    void *base = mmap(
        NULL, 
        total_size,
        PROT_READ | PROT_WRITE,
        MAP_PRIVATE | MAP_ANONYMOUS, 
        -1, 
        0
    );

    if (base == MAP_FAILED) {
        perror("mmap failed");
        _exit(127);
    }
    
    if (mprotect(base, page_size, PROT_NONE) != 0) {
        perror("mprotect front guard failed");
        _exit(127);
    }

    void* tail_guard = (char*)base + page_size + rounded_payload_size;
    if (mprotect(tail_guard, page_size, PROT_NONE) != 0) {
        perror("mprotect tail guard failed");
        _exit(127);
    }

    struct guarded_region region;
    region.mmap_base = base;
    region.usable_ptr = (char*)base + page_size;
    region.total_size = total_size;
    region.offset = offset;

    return region;
}

void destroy_guarded_region(struct guarded_region* region) {
    if (munmap(region->mmap_base, region->total_size) != 0) {
        perror("munmap failed");
    }
}

/*
    lock_page() is used to make a large allocation region 
    PROT_NONE. 

    This is done when the large allocation is placed into the cache.
    
    mprotect() is used to change the permissions of the page.

    madvise() with MADV_DONT_NEED is used to prompt the kernel to 
    immediately discard and free the physical pages associated
    with the region. This functions as a zero-filled reset. 
    The next time the program needs to use the memory region, it will 
    get a fresh, zero-filled page.

*/
void lock_page(void* base, size_t region_size) {
    if (mprotect(base, region_size, PROT_NONE) != 0) {
        perror("mprotect page protect has failed");
        exit(EXIT_FAILURE);
    }

    if (madvise(base, region_size, MADV_DONTNEED) != 0) {
        perror("madvise MADV_DONTNEED failed"); 
        exit(EXIT_FAILURE);
    }
}

/*
    unlock_page() is used to reactivate a large region 
    that was previously in the cache. 

    It utilizes mprotect() to change the permissions from PROT_NONE
    to be readable and writable again (PROT_READ | PROT_WRITE).
*/
void unlock_page(void* base, size_t region_size) {
    if (mprotect(base, region_size, PROT_READ | PROT_WRITE) != 0) {
        perror("mprotect page unprotect has failed");
        exit(EXIT_FAILURE);
    }
}


void fisher_yates_shuffle(uint16_t *indicies, size_t length) {

    for (size_t i = 0; i < length; i++) indicies[i] = i;

    for (size_t i = length - 1; i > 0; i--) {
        int j = _generate_random_number(i);

        int tmp = indicies[i];
        indicies[i] = indicies[j];
        indicies[j] = tmp;
    }
}